repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^.*\.cache/|^.*\.egg-info/
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-ast
  - id: debug-statements
  - id: check-yaml
    exclude: .gitlab-ci.yml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
    - --target-version=py310
    - --extend-select=UP,I
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
  hooks:
  - id: black
    args:
    - --preview
    - --enable-unstable-feature=string_processing
  - id: black-jupyter
    args:
    - --preview
    - --enable-unstable-feature=string_processing
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    args:
    - --convention=google
    - --add-ignore=D415,D205,D1
    additional_dependencies:
    - tomli
- repo: https://github.com/jsh9/pydoclint
  rev: 0.5.9
  hooks:
  - id: pydoclint
    args:
    - -aid=True
    - --style=google
    - -athd=False
    - -crt=False
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.42.0
  hooks:
  - id: markdownlint
    args:
    - --disable=MD013
    - --disable=MD024
    exclude: ^docs/.*
- repo: https://github.com/keewis/blackdoc
  rev: v0.3.9
  hooks:
  - id: blackdoc
    additional_dependencies:
    - black==24.8.0
  - id: blackdoc-autoupdate-black
